language: php

# Allows use container-based infrastructure
sudo: false

php:
 - 7.2

# Start mysql service
services:
  - postgresql


# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit
env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=29
    - SYMFONY_VERSION="4.2.*" DB=postgresql

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

addons:
  postgresql: "9.5"

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
  # - timedatectl set-timezone Europe/Paris
  - rm -rf var/cache/*

install:
  - composer install
  - cp app/config/parameters_travis.yml.dist app/config/parameters.yml
  - rm -rf var/cache/*
  # - travis_retry php bin/console doctrine:database:create --env=test
  # - openssl genrsa -passout pass:passphrase -out var/jwt/private.pem -aes256 4096
  # - openssl rsa -passin pass:passphrase -pubout -in var/jwt/private.pem -out var/jwt/public.pem

  - ./bin/phpunit install
# Commands to be run before your environment runs.

before_script:
  - psql -c 'create database shakit_test;' -U postgres

# Run script
script:
  # - vendor/bin/behat -v
  - ./bin/phpunit
  # this checks that the source code follows the Symfony Code Syntax rules
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config
  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig templates
  # this checks that the XLIFF translations contain no syntax errors
  - ./bin/console lint:xliff translations
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
  # this checks that the composer.json and composer.lock files are valid
  - composer validate --strict
  # this checks that Doctrine's mapping configurations are valid
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

notifications:
  email: false
