App\Entity\Recipe:
    type: entity

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 50
        description:
            type: text
            nullable: true

    manyToMany:
        ingredients:
            targetEntity: Ingredient
            inversedBy: recipes