# api/config/api_platform/resources.yaml
resources:
    App\Entity\Recipe:
        shortName: 'Recipe'
        description: 'recipe'
        # iri: 'http://schema.org/Recipe'
        attributes:
            pagination_items_per_page: 25

    App\Entity\Ingredient:
        shortName: 'Ingredient'
        description: 'ingredient'
        # iri: 'http://schema.org/Ingredient'
        attributes:
            pagination_items_per_page: 25